services:
  identityservice:
    build: .
    ports:
      - "7237:7237".
    environment:
      - ASPNETCORE_URLS=http://+:7237
      - DB_USER=sa
      - DB_PASSWORD=Your_password123
      - DB_SERVER=mssql
      - DB_DATABASE=tradeportdb
    networks:
      - my_network
    #volumes:
    # - "C:/wwwroot/uploads/images:/app/wwwroot/uploads/images" # Corrected volume path for Windows
networks:
  my_network:
    external: true
