version: "3.9"

services:
  identityservice:
    build:
      context: ..
      dockerfile: UserManagement/Dockerfile   # Path to your existing Dockerfile
    container_name: identityservice
    environment:
      - AWS_REGION=ap-southeast-1
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8087:80"
    networks:
      - my_network

networks:
  my_network:
    external: true
